# Workflow name
name: Build and Publish Storybook to GitHub Pages
run-name: ${{ github.actor }} is publishing Storybook

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build-storybooks
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "./storybook-static"
      - run: node scripts/server-storybooks.js
      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
