# Workflow name
name: Build and Publish Storybook to GitHub Pages
run-name: ${{ github.actor }} is publishing Storybook

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Install and Build 🔧
        run: | # Install npm packages and build the Storybook files
          npm install
          npm run build:dev:ci
          npm run build-storybooks
      - name: Prepare GitHub Pages content
        run: npm run prepare-gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages-dist
